# Primera Etapa
FROM node:18.7.0-alpine as build-step

RUN mkdir -p /app
WORKDIR /app

COPY package.json /app

RUN npm install 
#&& npm cache clean

#COPY . /app

#RUN npm run build --prod

# Segunda Etapa
#FROM nginx:1.17.1-alpine as web-server

#COPY --from=build-step /app/dist /usr/share/nginx/html